### ISSUE TITLE
Slide numbers aren't preserved

### ISSUE THREAD

**Issue by FlorianPfaff** [monperrus/ExpandAnimations#10]
Hi. Firstoff, this is a great extension and works (since 0.40) almost entirely as expected. There is just one issue: the slide numbers aren't preserved and will go up with any bullet point appearing.
Anyways, I can understand if fixing that issue is out of scope for this project, but thanks for considering it, and most of all thanks for this great extension.

**Comment by timkittel** [comment]
Hi Martin,
I have just forked the repo as I would love to implement this, but I have barely any experience with basic and the libreoffice API. Would you be willing to give me some pointers?
Tim

**Comment by monperrus** [comment]
That would be great to have your contributions.

I would suggest to have a look at https://api.libreoffice.org/

**Comment by goldmanm** [comment]
It seems like we need to be able to access the [SlideNumberShape](https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1presentation_1_1SlideNumberShape.html) and convert it to a constant number before duplicating the slides with animations.

**Comment by kskollepara** [comment]
Has this issue been resolved? I am using version 0.13 and still face the same problem.

Please let me know if I am missing something. Thank you

**Comment by gpiat** [comment]
This is still an issue for me, all my slide numbers are incremented with the animation slides. I'm running LibreOffice Version 7.3.7.2 on Ubuntu.

As far as I know, there are 4 ways of inserting slide numbers:
- `Insert > Slide Number`
- `Insert > Field > Slide Number`
- Editing the footer in the slide master
- `Insert > Header and Footer... > (check the slide number in dialog box)`

Methods 1, 2, and 2 are not immune to re-numbering. When I try the fourth method, I can't get it to number all my slides consistently (most slides just aren't numbered), but it *is* immune to re-numbering on the slides that *are* numbered. However, exporting to PDF changes the font and forcibly inserts the total number of slides.
