### ISSUE TITLE
BASIC runtime error. Property or method not found: AttributeName.

### ISSUE THREAD

**Issue by flyingfalling** [monperrus/ExpandAnimations#13]
Errors in this function it seems:

' checks if the given animation node changes a shape's visibility
function isVisibilityAnimation(animNode as Object) as Boolean
    isVisibilityAnimation = HasUnoInterfaces(animNode, ANIMSET) and _
                            (animNode.AttributeName = VISATTR)
end function

I can send slides if desired.

**Comment by MaximeMaW** [comment]
I am experiencing the same issue (LibreOffice Version: 4.3.3.2 Build ID: 430m0(Build:2), Debian Jessie)

**Comment by bjmc** [comment]
I'm getting the same error, on LibreOffice

> Version: 5.1.6.2
> Build ID: 1:5.1.6~rc2-0ubuntu1~xenial2
> CPU Threads: 4; OS Version: Linux 4.4; UI Render: default; 
> Locale: en-US (en_US.UTF-8); Calc: group

**Comment by monperrus** [comment]
Does #27 fix your problem? WDYT?

**Comment by monperrus** [comment]
Closed per #27

See new packaged file at https://github.com/monperrus/ExpandAnimations/blob/master/dist/ExpandAnimations-0.5.oxt
