### ISSUE TITLE
shortcircuiting "and"

### ISSUE THREAD

**Issue by zurzir** [monperrus/ExpandAnimations#18]
I think basic logical "and" behavior is not short circuting, so this code should give an error on a non-existent attribute:

```
function isVisibilityAnimation(animNode as Object) as Boolean
    isVisibilityAnimation = HasUnoInterfaces(animNode, ANIMSET) and _
                            (animNode.AttributeName = VISATTR)
end function
```

tried on this:

http://www.psc.org.br/wp-content/uploads/2016/09/sample.ppt

**Comment by monperrus** [comment]
Would you propose a pull-request?

**Comment by zurzir** [comment]
Unfortunately, I will not have the time now to prepare a pull. If someone is facing this problem, one could try (untested) 
```
function isVisibilityAnimation(animNode as Object) as Boolean
    isVisibilityAnimation = HasUnoInterfaces(animNode, ANIMSET)
    If isVisibilityAnimation Then
         isVisibilityAnimation = animNode.AttributeName = VISATTR
    End If
end function
```
