### ISSUE TITLE
Inadmissible value or data type

### ISSUE THREAD

**Issue by tuncK** [monperrus/ExpandAnimations#22]
I had previously used the extension without problems, but now I have Libreoffice 6.0.  When I attempt to use the extension on slides.odp, the program starts by generating slides-expanded.odp, but later quits with error:

`Inadmissible value or data type. Index out of defined range.`

For the problem, Basic editor points to the line 208, which is:
`dim visibility(UBound(shapes), nFrames-1) as Boolean`

**Comment by georoen** [comment]
Experiencing the same error here...

**Comment by monperrus** [comment]
Duplicate of #8, please comment or subscribe to #8.
