### ISSUE TITLE
Slide number progresses in expanded view

### ISSUE THREAD

**Issue by tim-tx** [monperrus/ExpandAnimations#23]
If I put slide numbers in the footer, the number still progresses with "animations" in the expanded version. Usually it would still be considered one slide though.

**Comment by monperrus** [comment]
Thanks for the suggestion. Let's hope that somebody picks this issue and gets it fixed!

**Comment by Bessonov** [comment]
Duplicate of #10

**Comment by monperrus** [comment]
Thanks!
