### ISSUE TITLE
BASIC Runtime Error in LibreOffice 3.5.4.2 on Ubuntu 12.04

### ISSUE THREAD

**Issue by sameerpanje** [monperrus/ExpandAnimations#4]
Hi,

Thanks for this wonderful extension. Was almost about to make that unwanted switchback to Microsoft Office due to the lack of font embedding support in ODF. Till I came across this life-saver. I can live with the basic appear animation on my slides (mainly bullet point-driven sales pitches) and the portability of PDF is almost universal. I downloaded it yesterday & it worked great with a couple of test slides.

I've hit this hitch though. I have this presentation with 7 slides which is the reason that led me to download this extension. The first slide has only the Title element. The next 4 slides have a Title element & a text box with bullet points. The sixth has a Title with a bitmap. I have animated the bullet point text-boxes and the bitmap with the appear effect. The last one is only the Title.

When I tried compiling the presentation using this extension, I run into a BASIC Runtime error that has the description <strong>Property or method not found:createEnumerate</strong>. The script aborts and I'm left with an intermediate odp file named [original-filename]-expanded.odp & the script window with the line <strong>animNodes = effectNode.createEnumeration()</strong> highlighted. The intermediate odp file has the first 4 slides intact. Then there are seven copies of the 5th slide (the last one with animated bullet points). Then there is one with only the title of the slide with the bitmap...followed by one with the bitmap. The last slide is intact.

I have zilch idea of scripts & macros. So have no clue what is going on. But I can follow instructions well. Any help resolving this problem would be greatly appreciated. Apologies if any of my post is incoherent. Please ask for specifics that may help you understand this better & I'll cooperate to my best.

Thanks a million. :)

Sam

**Comment by pixelshot91** [comment]
I have the same problem and fix it by adding checking `HasUnoInterfaces(effectNode, ENUMACCESS)` returns true before calling the `createEnumeration()` function.

I created a PR here : #51 

I attached to the PR an example of file that trigger the bug. Should I put it in the test/ folder to prevent futur regression ?
