### ISSUE TITLE
Support for Notebookbar

### ISSUE THREAD

**Issue by errotu** [monperrus/ExpandAnimations#41]
Once again, thanks for your work!
It would be great if the option to trigger ExpandAnimations would not only be found under Tools>>Add-ons>>Expand animations but also in the NotebookBar "Extension"-Tab. Some further information regarding this [is provided here](https://wiki.documentfoundation.org/Development/NotebookBar/Extensions).

**Comment by errotu** [comment]
I've provided a commit for this enhancement. Unfortunately, it seems like the context value is not working properly. The ExpandAnimations-Icon is also displayed in Writer at the moment.

**Comment by monperrus** [comment]
Great, could you do a WIP pull-request? Thanks!

**Comment by errotu** [comment]
Sorry, I forgot. Done by now!
