### ISSUE TITLE
Doesn't work on Impress 7.0.0.3

### ISSUE THREAD

**Issue by deisi** [monperrus/ExpandAnimations#49]
The plugin runs, but the exported pdf does not contain any sort of expanded animation. It is basically the same as just clicking on the export pdf button.

**Comment by anisghaoui** [comment]
I can confirm. It works on prior versions.

**Comment by kamdh** [comment]
Works for me on 7.0.1.2 in Linux

**Comment by vkovalcik** [comment]
Same as OP: Windows 10 and this extension didn't work in 7.0.0.2, but I haven't tested the current 7.0.1. Installed 6.4.6 instead and it works well.

**Comment by deisi** [comment]
I just tested with 7.0.1.2 and it works. I close this thus.
