### ISSUE TITLE
Question: specify page range when exporting?

### ISSUE THREAD

**Issue by MatthieuStigler** [monperrus/ExpandAnimations#58]
Hi

Thanks for this great extension which fills an important gap!

Quick question: is it possible to restrict the range of the pages to be exported to pdf (as is possible with OO's standard export to pdf)? I understand though that at this point there is no dialog when exporting (i.e. just go to Tools -> add-Ons -> Expand)?

Thanks!

**Comment by monperrus** [comment]
no, this option does not exist.
you can always postprocess the pdf with a tool such as pdfmod or pdftk.

**Comment by MatthieuStigler** [comment]
ok, thanks for the fast answer!
